replicaCount: 1

image:
  repository: quay.io/swapnilshekade/rydercup-api-service
  tag: new13
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8009
  targetPort: 8000

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1000Mi"
    cpu: "1000m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
