# MongoDB image
image:
  repository: mongo
  tag: "6.0"
  pullPolicy: IfNotPresent

# Service config
service:
  type: ClusterIP
  port: 27017

# MongoDB credentials
auth:
  username: admin
  password: admin

# Persistent storage (optional)
persistence:
  enabled: false   # set to true and configure storageClass if you want PVCs
  size: 10Gi


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80  # optional
