apiVersion: v1
kind: Service
metadata:
  name: {{ include "rydercupva.fullname" . }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "rydercupva.name" . }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
