replicaCount: 1

image:
  repository: quay.io/swapnilshekade/genai_fileservice
  tag: preprod-v2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8004
  targetPort: 8003

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 60

# Istio configs
istio:
  enabled: true
  gateway:
    name: ezaf-gateway
    namespace: istio-system
  hosts:
    - "fileservice.${DOMAIN_NAME}"
  tls:
    selfSigned: true
