replicaCount: 2

image:
  repository: quay.io/swapnilshekade/rydercup-sampleui
  tag: new12
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60